#!/bin/bash

OPEN=/usr/bin/open
ARGS="-W -a WriteRoom"

#########################
# If there is no filename
if [ -z "$1" ]; then
    $OPEN $ARGS
    exit $?
fi

########################
# If there is a filename

# Create the file if it doesn't exist
[ -e "$1" ] || touch "$1"

# Open the file
$OPEN $ARGS "$1"

# Check if the file is zero size
# If so, delete it so googlecl doesn't upload it
# -s  file is NOT zero size
[ -s "$1" ] || rm "$1"
